env:
  browser: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: './tsconfig.json'
extends:
  - airbnb-typescript/base
  - prettier
plugins:
  - '@typescript-eslint'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
rules:
  no-console: off
  import/prefer-default-export: off
  no-param-reassign: off
  import/no-cycle: off
