env:
  browser: true
  es6: true
extends:
  - airbnb-base
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  no-console: off
  import/prefer-default-export: off
  no-param-reassign: off
  import/no-cycle: off
