version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - next
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - $HOME/.npm
      - run:
          name: test
          command: npm run test
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/coverage-final.json
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: npm run release || true
